name:  Question
description: Question Submission
title: "[Question]"
labels: ["question"]
projects: ["add_project"]
assignees: add github name
body:
  - type: textarea
    id: Question
    attributes:
      label: Question
      description: Question submission for group members
      placeholder: Tell us what you see
      value: "Question submission details"
    validations:
      required: true
  - type: dropdown
    id: TF-Groups
    attributes:
      label: Issue dependency with other TF Groups
      multiple: true
      options:
        - No Dependency
        - Admin
        - Address
        - Base
        - Data Platform
        - Dev Advocacy
        - GERs
        - Schema
        - Transportation
