name: Pre-commit Code Style Checks

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Python3 environment for pre-commit
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Run pre-commit checks
        uses: pre-commit/action@v3.0.1
        with:
          extra_args: --from-ref origin/main --to-ref HEAD
