name: "Test Splitter"
on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [main]
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # From AWS Glue and Databricks latest runtimes
        # Must be coupled due to incompabilities across versions
        version: [{python: "3.10", pyspark: "3.3.0"}, {python: "3.11", pyspark: "3.5.0"}]
    steps:
    - name: Check out repository
      uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.version.python }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.version.python }}
    - name: Check Python version
      run: python --version
    - name: Upgrade pip
      run: pip install --upgrade pip
    - name: Install packages
      run: pip install -r requirements.txt
    - name: Install pyspark ${{ matrix.version.pyspark }}
      run: pip install pyspark==${{ matrix.version.pyspark }}
    - name: Run tests
      run: pytest -vv
